Create database IMDb;


Select * from [IMDb dataset]

                                                  --- IMDb Data Analysis ---
--1 Total numbers of Movies--

Select Count(*) as Total_Movies from [IMDb dataset]

--2 Top 10 movies that generated the highest Revenue --

Select Top 10 Round(Sum(Revenue_Millions) ,2) as Highest_Revenue, Title from [IMDb dataset]
Group by Title 
Order by Highest_Revenue desc;

--3 Revenue ranking based on genre --

Select Round(Revenue_Millions, 2) as Revenue, Genre,
Dense_Rank() over(order by Round(Revenue_Millions, 2) desc) as 'Rank_dense'
from [IMDb dataset]

--4 Directors who generated the highest revenue --

Select Round(Sum(Revenue_Millions) ,2) as Highest_Revenue, Director from [IMDb dataset]
Group by Director 
Order by Highest_Revenue desc;

--5 Revenue by Year --

Select Round(Sum(Revenue_Millions) ,2) as Highest_Revenue, Years from [IMDb dataset]
Group by Years 
Order by Highest_Revenue desc

--6 Movies generated highest Revenue in each year --

Select Years, Title, Revenue_Millions
from (
    Select Years, Title, Revenue_Millions,
           Row_Number() Over (Partition by Years order by Revenue_Millions desc) as Rank
    from [IMDb dataset]
) rank_
where Rank = 1

--7 Higesht Rated Movies--

Select Title, Director, Rating from [IMDb dataset]
Order by Rating desc;

--8 Each Director highest rated movie --

Select Director, Title, Rating
from (
      Select Director, Title,  Rating,
	         ROW_NUMBER() Over (Partition by Director Order by Rating desc) as Rank
			 from [IMDb dataset]
) rating
where Rank = 1

--9 Average Rating--

Select AVG(Rating) as Avg_Rating from [IMDb dataset]

--10 Number of Movies generated by each Director --

Select Count(Title) as Total_Movies, Director
from [IMDb dataset]
Group by Director
Order by Total_Movies desc;
      
--11 Movies Runtime --

Select Title, Director, Runtime_Minutes from [IMDb dataset]
Order by Runtime_Minutes desc

--12 Number of Genres --

Select Count(Title) as Total_Movies, Genre
from [IMDb dataset]
Group by Genre
Order by Total_Movies desc;

--13 Total number of Votes --

Select Sum(Votes) as Total_Votes from [IMDb dataset]

--14 Top 10 highly Voted movies --

Select Top 10 Votes, Title from [IMDb dataset]
Order by Votes desc;

--15 Top 10 highly Meta Score movies --
 
Select Top 10 Metascore, Title, Director from [IMDb dataset]
Order by Metascore desc;
